### ISSUE TITLE
Where are FormAction, EntityFormField, BooleanFormField, FreeTextFormField

### ISSUE THREAD

**Issue by macasas** [MatheusFaria/rasa-bot-example#1]
Hi Matheus

I've found this interesting because of the way you use it to collect slot, but where are these in rasa, I cannot find them anywhere, is this an older version, if so, how would this be done in the latest version

from rasa_core.actions.forms import FormAction, EntityFormField, BooleanFormField, FreeTextFormField

**Comment by MatheusFaria** [comment]
You should be able to find them at [here](https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/actions/forms.py)

**Comment by macasas** [comment]
Thanks. I have been using a local version, and that file isn't in it :-( It is now, thanks a lot!
